### ISSUE TITLE
Make Rh-Che PR-check (automated commit tests + smoke test suite) great again

### ISSUE THREAD

**Issue by ScrewTSW** [redhat-developer/che-functional-tests#310]

**Comment by rhopp** [comment]
The latest run of this job failed on tests. This is probably because the deployment script was unable to annotate the route (which results of the che deployment being broken) - https://ci.centos.org/job/devtools-rh-che-rh-che-prcheck-dev.rdu2c.fabric8.io/281/consoleFull

Relevant part of logs:
```
The Route "rhche" is invalid: metadata.annotations: Invalid value: "kubernetes.io~1tls-acme": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]')
```

This bug in openshift was already reported: https://bugzilla.redhat.com/show_bug.cgi?id=1524305

**Comment by ibuziuk** [comment]
@rhopp do we have a dedicated issue on HK to in order to raise SD team awareness ?

**Comment by rhopp** [comment]
@ibuziuk I didn't create any... I didn't know this deserves HK issue.

**Comment by ibuziuk** [comment]
@rhopp well I do believe we should create it since this is a blocker for rhche PR verifiacation

**Comment by rhopp** [comment]
https://github.com/redhat-developer/rh-che/pull/769 was merged today. PR check is green again.
I've sent simple PR to almighty jobs: https://github.com/openshiftio/openshiftio-cico-jobs/pull/727 changing the status message for passing job (replacing `https` in url with `http`).
As this last pending PR check is just a cosmetic issue, I'm closing this one as done.

**Comment by ibuziuk** [comment]
@rhopp great job!
