### ISSUE TITLE
Bayesian for package.json failed

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/che-functional-tests#464]
Waiting for Bayesian in package.json timeouted. Affected job: https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/147/console

**Comment by ibuziuk** [comment]
@Katka92 Any investigation details?

**Comment by Katka92** [comment]
It seems to me like it last longer that we suppose it should - so sometimes when it last longer than usually it fails. Do you think that it can be related to infra issue? I wouldn't say that Bayesian is broken as it passes in most runs.

**Comment by ibuziuk** [comment]
> Do you think that it can be related to infra issue?

 @Katka92 hard to say, we need more details

**Comment by invincibleJai** [comment]
I was going through logs, from build 143 to 177 for Bayesian it has failed in 146, 171 and 177 that is 3 out of 34 times. 

This looks problem with services getting the timeout (504) or some latency issue. Similar issue I observed with VSCode Extension as well as it's consuming same LS https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/issues/270 and has been fixed and have not observed recently though.

**Comment by tisnik** [comment]
@invincibleJai yes, we need to check if the problem is on API side and what the problem is. I also seen couple of 504 errors for other API calls.

**Comment by ibuziuk** [comment]
@tisnik @invincibleJai folks, have you got a chance to investigate?

**Comment by invincibleJai** [comment]
@ibuziuk yes some optimizations were done to improve the time to query for CVE against EVPs and since then have not observed any 504's. This reflects even in builds https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/ None of the builds since April 10th have failed.

as you know `504 - gateway time out ` can occur due to various other reasons as well like latency or load. For now, we can mark it close or have an open eye for the next couple of days. @tisnik is working on load testing, we'll get these insights from there as well.

**Comment by ibuziuk** [comment]
> This reflects even in builds https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/ None of the builds since April 10th have failed. 

@invincibleJai great, thanks. Let's wait for a couple of days and close if it will not be reproducible via periodic CI. cc @Katka92

**Comment by Katka92** [comment]
@ibuziuk @invincibleJai Great job as these failures really almost gone. But tests sometimes fails because of Bayesian error is not here, e.g. https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1b/251/console. But yeah, that happened 13th April, so we can wait and see if it will happen again. If this error won't be present for this week, I'll close the issue. Thank you all! I'll write a comment here to let you know once I see that error again.

**Comment by Katka92** [comment]
It seems like this issue was solved. I haven't seen the error in periodic CI from my last comment. Closing.

**Comment by Katka92** [comment]
Happened again today https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/580/console

**Comment by ScrewTSW** [comment]
it also happened on 4th of may on prod-2 https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/592/console
on prod-1a: https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/377/console
and prod-2a on 5th: https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/383/console

**Comment by tisnik** [comment]
----- Original Message ----- 

> it also happened on 4th of may on prod-2
> https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/592/console
> on prod-1a:
> https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/377/console
> and prod-2a on 5th:
> https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/383/console

Our load tests show similar behavior. I'm cooperating with devels to fix this issue.

Thanks,
Pavel

**Comment by tisnik** [comment]
> and prod-2a on 5th: https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/383/console

Is it possible to explain which call went wrong, what was the payload and how the response looked like please?

**Comment by Katka92** [comment]
@tisnik These are selenium tests and the test were waiting for span element to appear:
```
Unable to locate element: {"method":"css selector","selector":"span.tooltipTitle"}
```
This is element with an error, but as you see from the screenshoft, no error is present.
![image](https://user-images.githubusercontent.com/29278800/57276331-84b4d580-70a1-11e9-8c18-4e3ffcbd9ed6.png)

**Comment by ScrewTSW** [comment]
> > and prod-2a on 5th: https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/383/console
> 
> Is it possible to explain which call went wrong, what was the payload and how the response looked like please?

```
[pool-1-thread-1] ERROR org.eclipse.che.selenium.core.inject.SeleniumTestHandler - Test BayesianPackageJson.checkBayesianError failed. Error: Expected condition failed: waiting for visibility of Proxy element for: DefaultElementLocator 'By.cssSelector: span.tooltipTitle' (tried for 10 second(s) with 500 MILLISECONDS interval)
```

**Comment by miteshvp** [comment]
Root cause of the issue was identified to be one of the cron jobs that syncs all the CVE into our graph every 6 hours. This results into high write transactions during the said window causing LSP calls to take longer than expected. Again, it would be super useful if you can also log error response codes if possible in case there is a real 504 as against the test suite timeouts. The fix has already been promoted to production. I will be following this issue in case it resurfaces.

**Comment by Katka92** [comment]
This issue is still present. Reopening.

**Comment by miteshvp** [comment]
Just to be clear, is it test suite timeout or real 504s ? Can you share the package and its version used for testing as well?

**Comment by miteshvp** [comment]
@Katka92 - Just to be clear, is it test suite timeout or real 504s ? Can you share the package and its version used for testing as well?

**Comment by Katka92** [comment]
@miteshvp The timeout is 10 seconds for the error to appear. It is just estimate in our tests, no SLA. If you happen to know what timeout should be set here, it would be great. 
For json test we use the dependency: ``` "serve-static": "1.7.1" ```. 
I do not know how to verify that it is 504 error as far as we are checking only what user can see in the UI. 
cc @tisnik

**Comment by tisnik** [comment]
@Katka92 SLA defined and _planned_ so far (for CVE part):

Success rate of LSP calls (to flag CVEs) to analytics service: 95%
Latency for LSP calls (to flag CVEs) to analytics service: 2 seconds

so the 10 seconds timeout is fair (IMHO), given we need to make sure the LSP plugin itself have the time to update UI.

**Comment by miteshvp** [comment]
@Katka92 @tisnik - SLA of 2 seconds is per EPV. How many EPVs do we have in package.json?

**Comment by Katka92** [comment]
@miteshvp We have only one project in a workspace and only two dependencies in package.json:
```
"express": "^4.13.4",
"serve-static": "1.7.1"
```
So from what I understand the time when error is shown should not be more than 4 seconds. We have 10 in our tests, so that should be fine, right?

**Comment by invincibleJai** [comment]
@Katka92 i was trying to get those dependencies from code 

for npm : `serve-static` https://github.com/redhat-developer/che-functional-tests/blob/51ea12ddaddf4c8679b2af7269d39e6af041e174/tests/src/test/java/redhat/che/functional/tests/PackageJsonTestCase.java#L40

for maven : `logback-core` https://github.com/redhat-developer/che-functional-tests/blob/e55958a5b04fd91ff9387786cc8b2dbd30ac2b83/tests/src/test/java/redhat/che/functional/tests/PomTestCase.java#L28

but couldn't find express, so am I looking at the right place?

Are all these test jobs run against Prod or prod-preview?

**Comment by Katka92** [comment]
@invincibleJai In our test we add the dependency which should cause the error to be shown. But in the project we use there already is one dependency defined. You can see printscreen of the package.json in my comment above https://github.com/redhat-developer/che-functional-tests/issues/464#issuecomment-489925304. 
Our tests are running against all production cluster and against prod-preview cluster 2a. 
You can find all our jobs here https://github.com/redhat-developer/rh-che#periodic-functional-tests and by clicking on them you can see jobs on Jenkins. All screenshots from the runs that failed can be found here http://artifacts.ci.centos.org/devtools/rhche/ by accessing folder named as a job you are interested in, then folder of a exact run.

**Comment by invincibleJai** [comment]
thanks @Katka92 

So am assuming we are trying below scenarios : 
1. Add Dependency to `pom.xml` and `package.json` which has vulnerability i.e serve-static@1.7.1 and verify if markers are shown
2. Close manifest file which we edited above and reopen, validate again to verify if markers are shown

are there any scenarios am missing?

**Comment by tisnik** [comment]
@Katka92 is it possible to temporarily increase the timeout to 30 seconds please? It will be just temporary settings until the Analytics team implement the monitoring for API side.

**Comment by Katka92** [comment]
@invincibleJai 
I think you are right, but I would like to make it more precise. The ``` serve-static ``` dependency is used only for ``` package.json ```, for ``` pom.xml ``` the dependency is ``` logback-core ``` as you can see here: https://github.com/redhat-developer/rh-che/blob/master/functional-tests/src/test/java/com/redhat/che/functional/tests/BayesianPomXml.java#L38. 
Next thing worth mentioning is that we are skipping test for reopening file for ``` pom.xml ``` - as the issue is still open https://github.com/redhat-developer/rh-che/issues/1256. Do you happen to know if this should work correctly? We can then enable the test again. 

@tisnik It is possible but it would take a lot of effort on our side. From what I understand, changing it to 30 seconds have no value for you, it is just workaround for our tests, right? 
As far as test is failing intermittently and the last fail is one week old, I am OK with having that as it is and treating that as a known issue. If the test starts failing more often, we can increase the timeout as you suggested. Are you OK with that?

**Comment by invincibleJai** [comment]
@Katka92 yes am aware for `pom.xml` has a dependency `logback-core` which is correct. One observation i have 
When the issue was logged for failure due to Bayesian LS , Even the screenshots generated used to have snapshots for the manifest file i.e `package.json/pom.xml` as in http://artifacts.ci.centos.org/devtools/rhche/devtools-rh-che-periodic-prod-2aProd/147/screenshots/

it has http://artifacts.ci.centos.org/devtools/rhche/devtools-rh-che-periodic-prod-2aProd/147/screenshots/com.redhat.che.functional.tests.BayesianPackageJson.checkBayesianError_time-1553624586042-millis.png which clearly shows bayesian error.

However in recent failures eg http://artifacts.ci.centos.org/devtools/rhche/devtools-rh-che-periodic-prod-2/636/screenshots/

There are no screenshots showing snapshot of open manifest file as above. http://artifacts.ci.centos.org/devtools/rhche/devtools-rh-che-periodic-prod-2/636/screenshots/

So can't it possible due to some issue opening of manifest file itself failed and so bayesian test failed.??

Is there any test which validated file open success?

**Comment by tisnik** [comment]
@Katka92 "it is just workaround for our tests, right?" well not exactly. @invincibleJai is under impression the problem might be somewhere else, not in the slow API. And while we don't have proper monitoring & logging yet, we might try to increase the timeout and check if the error message appear even later.

**Comment by Katka92** [comment]
@invincibleJai You are absolutely right. We have an issue for that here: https://github.com/redhat-developer/che-functional-tests/issues/483 So the two logs for 2 and 1a should be reported in another issue. Anyway the fail on 2a is still about bayesian:
logs:  https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/383/console
screenshots: http://artifacts.ci.centos.org/devtools/rhche/devtools-rh-che-periodic-prod-2aProd/383/screenshots/

@tisnik So it would help you to increase timeout and add logging for the time that was needed, right? OK, if it has value for you, I can increse a timeout and add log in our test.

**Comment by invincibleJai** [comment]
> @invincibleJai You are absolutely right. We have an issue for that here: #483 So the two logs for 2 and 1a should be reported in another issue. Anyway the fail on 2a is still about bayesian:
logs: https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/383/console
screenshots: http://artifacts.ci.centos.org/devtools/rhche/devtools-rh-che-periodic-prod-2aProd/383/screenshots/

@Katka92 thanks a lot for the info. 

Have checked below  from last 6 days i.e 8th may when @miteshvp updated thread https://github.com/redhat-developer/che-functional-tests/issues/464#issuecomment-490346350 with fix as we encountered 504's which was even confirmed by @tisnik as well.

1. https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/
2. https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/
3. https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/

For all above, since then fix went in I have not seen any failure for baysian. There are failures which is associated with https://github.com/redhat-developer/che-functional-tests/issues/483 and this is not related to bayseian right? Let me know your thoughts

https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2aProd/383/console was on may 5th.

**Comment by Katka92** [comment]
@invincibleJai Yes, the #483 is failure not related to bayesian. Thank you very much for your time, I'll keep it open for a while to keep tracking and close it if it will not be observed in few days.

**Comment by Katka92** [comment]
Haven't seen this failure for ten days. Closing.

**Comment by Katka92** [comment]
Bayesian error not showed in time for the job https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-1a/657/console. 
![image](https://user-images.githubusercontent.com/29278800/59823401-6c85d680-932e-11e9-9c12-cca7d5ea07e7.png)

**Comment by ScrewTSW** [comment]
Happened yesterday and today on `starter-us-east-1b`

**Comment by Katka92** [comment]
Seen again on starter-us-east-2 when checking bayesian after reopening a file https://ci.centos.org/job/devtools-rh-che-periodic-prod-2/1092/console

**Comment by ScrewTSW** [comment]
Closing in favour of rhche issue
