### ISSUE TITLE
Monitor workspace startup time on all clusters

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/che-functional-tests#467]
Task: Rewrite workspace-start jobs

There are jobs on osioperf which were reporting data about workspace startup time to Zabix [1] [2]. These jobs are failing now. Fix these jobs, add new jobs for cluster ```starter-us-east-1a``` ```starter-us-east-1b``` on production.
All these jobs should report data to Zabix. 

Improve job by watching for the dashboard to be open and the project imported.

[1] https://osioperf-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/che-start-workspace/
[2] https://osioperf-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/che-start-workspace-2a/

**Comment by l0rd** [comment]
From what I understand the new Job that monitors startup time is [workspace-startup-test](https://osioperf-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/workspace-startup-test/). And results are published on Zabbix [here](https://zabbix.devshift.net:9443/zabbix/screens.php?elementid=49).

@ScrewTSW Am i correct? What Che stack is used to for those tests? Will the 2 jobs mentioned in @Katka92 comment be deprecated?

A few feedbacks on the Zabbix generated charts:
- I would be nice if it could be a bar graph with each bar corresponding to a distinct run and with different color. That would allow to clearly identify the single runs.
- I don't understand the value of the 2 `*-request` metrics. They are almost invisible in the graph and it's not clear if `che_startWorkspace-time = che_createWorkspace-request + che_startWorkspace-request + ?`. Anyway, as it is it's just noise and I would rather remove them.
- The `[avg]` label in each row is weird because there is already an `avg` column and `last`, `min` and `max` are not averages. What does that mean? 

Something that worries me is that results are not constants at all: there can be 20s difference between 2 consecutive tries. And it looks like usually there is an alternance between one run and the other. I suspect that it can be related to images pull: sometimes images are already pulled in the node where the test is run and sometimes they are not. @amisevsk is that possible?

cc @rhopp @ibuziuk

**Comment by amisevsk** [comment]
> And it looks like usually there is an alternance between one run and the other. I suspect that it can be related to images pull: sometimes images are already pulled in the node where the test is run and sometimes they are not.

This sounds likely; there are a few issues I've been meaning to check on; kubernetes-image-puller is deployed currently but we haven't updated the list of cached images in a long time. Additionally, I need to look into how daemonsets manage mutable image tags (since I'm guessing the `theia:next` image we're running is now a few weeks out of date). Fixing this would likely require some minor work on kubernetes-image-puller.

**Comment by rhopp** [comment]
@l0rd 

> What Che stack is used to for those tests?

https://github.com/ScrewTSW/che-functional-tests/blob/467-feature-fix-workspace-startup-monitoring-jobs/che-start-workspace/che7_workspace.json

> Will the 2 jobs mentioned in @Katka92 comment be deprecated?

Yes. They are being replaced by Tibor's work (you have the correct link to that job). This one job will run workspace on all clusters & report to zabbix (instead of having separate jobs for each cluster as it was before)
> I would be nice if it could be a bar graph 

I've took a quick look and I didn't see any way how to do that. Further quick google search shows it's not implemented (or at least easily achievable): https://support.zabbix.com/browse/ZBXNEXT-1819

> I don't understand the value of the 2 *-request metrics. 

It's time for the HTTP response to get back. I have no objections removing this/including this in the overall time (but the stacked graph does that automatically ;-) )

>The [avg] label in each row is weird

Yep.. indeed it's weird. There is aggregation function to each item in the graph (avg,min,max), but changing that doesn't do anything and I cannot remove it. I think we can just ignore that label (it does nothing for us)

**Comment by l0rd** [comment]
@Katka92 @rhopp @ScrewTSW can we add the seconds it takes to start a workspace on the daily test summary on slack? I would use the max value for the last day. And I would also add the difference in % with the day before. 

For example: `ws-start 55s (-5%)`

**Comment by Katka92** [comment]
@l0rd OK, I can do that, no problem. :) Do you think about it as a temporary thingy to track this issue or would you like to add that permanently? Maybe it would be nice to have stopping time on daily report too?

**Comment by l0rd** [comment]
@Katka92 Permanently and +1 for stop time if it's easy to add

**Comment by ScrewTSW** [comment]
Closing issue, continuing in #511
