### ISSUE TITLE
Verify that all dev files work on prod-preview

### ISSUE THREAD

**Issue by Katka92** [redhat-developer/che-functional-tests#543]
Go through all dev files on prod-preview and verify they are OK.

**Comment by Katka92** [comment]
Tested (will be updated):

**Nodejs + angular-patternfly-demo-app**
-  Workspace startup - OK
-  commands:
   - commands fail ` che: start `, ` che: build `, ` che: lint ` fails on `error Couldn't find a package.json file in "/" `
   - command ` yarn intsall ` fails on `error Could not write file "/yarn-error.log": "EACCES: permission denied, open '/yarn-error.log'"error An unexpected error occurred: "EACCES: permission denied, mkdir '/node_modules'". `.
 
**Apache Camel + none project**
- Workspace startup - Failed
```
Error: Failed to run the workspace: "Unrecoverable event occurred: 'FailedCreate', 'Error creating: pods "workspace5rfnf112t9eh5984.maven-5cf8bd788-fw9bq" is forbidden: [maximum cpu usage per Pod is 6, but limit is 6424m., maximum memory usage per Pod is 3Gi, but limit is 3450109952.]', 'workspace5rfnf112t9eh5984.maven-5cf8bd788'"
```
**.NET Core + dotnet-web-simple**
- Workspace startup - OK
- commands:
   - ` che: update dependencies ` - OK
   - ` che: run ` -  OK

**Go + desktop-go-simple**
- Workspace startup - OK
- commands:
   - ` che: run outyet ` - fails with ` can't load package: package .: no Go files in /go `
   - ` che: test outyet ` - fails with ` can't load package: package .: no Go files in /go `
![Screenshot from 2019-07-11 13-59-22](https://user-images.githubusercontent.com/29278800/61049196-2202f180-a3e4-11e9-974c-82f9f934840a.png)

**Java Gradle + console-java-simple**
- Worksapce startup - OK
- commands:
   - ` che: gradle build ` - OK
   - ` che: gradle run ` - OK

**Java Maven + console-java-simple**
- Worksapce startup - OK
- commands:
   - ` che: maven build and run ` - OK
   - ` che: maven build ` - Once failed with ` [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project console-java-simple: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test failed: The forked VM terminated without saying properly goodbye. VM crash or System.exit called ? -> [Help 1] ` seconds run was successfull

**Nodejs Express Web Application + nodejs-crud-sample**
- Workspace startup - Fails with message ` Failed
Invalid project name found:'Nodejs Postgres Sample'. Name must contain only Latin letters,digits or these following special characters ._- `
![Screenshot from 2019-07-11 14-12-42](https://user-images.githubusercontent.com/29278800/61049906-faad2400-a3e5-11e9-8484-8180621e8be2.png)

**NodeJS MongoDB Web Application + nodejs-hello-world**
- Workspace startup - OK
- in project, there is web-nodejs-sample even if I chose nodejs-hello-world
- commands:
   - ` che: run the web app ` - fails on ` curl: (7) Failed to connect to localhost port 3000: Connection refused `
   - ` che: create test user ` - fails on ` npm ERR! enoent ENOENT: no such file or directory, open '/opt/app-root/src/package.json' `

**Nodejs React Web Application + nodejs-hello-world**
- Workspace startup - OK
- in project, there is web-nodejs-sample even if I chose nodejs-hello-world
- commands:
   - ` che: start the local server` - fails with ` sh: line 0: cd: /projects/react-redux-realworld-example-app: No such file or directory `
   - ` che: install all required dependencies ` - fails with ` sh: line 0: cd: /projects/react-redux-realworld-example-app: No such file or directory ` 

**PHP Laravel with MySQL + crud-php**
- Worksapce startup - OK
- project ` pdo ` is imported

**Comment by ScrewTSW** [comment]
NodeJS Angular Web Application - FAIL
===
* **devfile project is missing in the project list, can be imported manually using git**
* Workspace starts up
* Commands:
  * **start** - command fails (ng: not found)
  * **build** - command fails (ng: not found)
  * **lint** - command fails (ng: not found)
  * **yarn install** - error An unexpected error occurred: "https://registry.yarnpkg.com/rxjs/-/rxjs-6.4.0.tgz: ESOCKETTIMEDOUT".

Apache Camel based on Spring Boot - FAIL
===
* devfile project exists
* **workspace won't start because of quotas:**
```
Error: Failed to run the workspace: "Unrecoverable event occurred: 'FailedCreate', 'Error creating: pods "workspaceelmitsecigketh8h.maven-69b594f859-h2cq2" is forbidden: [maximum cpu usage per Pod is 6, but limit is 6424m., maximum memory usage per Pod is 3Gi, but limit is 3450109952.]', 'workspaceelmitsecigketh8h.maven-69b594f859'"
```

.NET Core - FAIL
===
* devfile project successfully imported
* workspace started
* Commands:
  * New terminal - opens a new "dotnet terminal"
  * update dependencies - OK
  * **run** - build fails
```
/usr/share/dotnet/sdk/2.2.301/NuGet.targets(121,5): error : Could not find a part of the path '/home/user/.nuget/packages/microsoft.aspnetcore.mvc.razor.viewcompilation/2.0.0-preview2-final'. [/projects/dotnet-web-simple/web.csproj]

The build failed. Please fix the build errors and run again.
```
  * 5000/tcp - opens a URL to the application deployment (unable to test because of `run`)

Go - FAIL
===
* **devfile sample project with name `example` doesn't exist** https://github.com/eclipse/che-devfile-registry/blob/master/devfiles/go/devfile.yaml#L7
* workspace started
* manual project using git worked
* **Project configuration is incorrect.**
  * The project was cloned into /projects/example
  * Go expects it to be in $GOPATH/src/github.com/golang/example/
  * $GOPATH points to /go:/projects
* Commands:
  * New terminal - opens a new go-cli terminal
  * **test outyet** - cd: can't cd to /projects/src/github.com/golang/example/outyet
  * **run outyet** - cd: can't cd to /projects/src/github.com/golang/example/outyet

Java Gradle - WARN
===
* devfile project successfully imported
* workspace started
* Commands:
  * New terminal - opens gradle terminal successfully
  * gradle build - success
  * gradle run - success, run successfull
  * **8080/tcp** - successfully opens up a new tab - THIS IS USELESS, there's no application deployment happening, it's just a single-run simple java hello world.

Java Maven - WARN
===
* devfile project successfully imported
* workspace started
* Commands:
  * New terminal - opens maven terminal
  * **maven build and run** - fail
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project console-java-simple: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test failed: The forked VM terminated without saying properly goodbye. VM crash or System.exit called ?
```
  * maven build - OK
  * maven build and run (again) - success - `Hello World Che!`
  * **8080/tcp** - opens a new tab pointing to a non-existsnt deployment - THIS IS USELESS, there's no application deployment happening, it's just a single-run simple java hello world.

**Comment by amisevsk** [comment]
A brief test of the (at the time of writing) available devfiles: https://gist.github.com/amisevsk/86ec3540da1b9b5ccd98aa23d4e9fafb

This includes the fixes in https://github.com/eclipse/che-devfile-registry/pull/38 and uses upstream `eclipse-che/nightly-centos`.

**Comment by ibuziuk** [comment]
Closing in favour of https://github.com/redhat-developer/che-functional-tests/issues/543
Please, report devfile specific issue in the rh-che and lets's not use `che-functional-tests` for any issue reporting from now on
